# **Завдання 1. Setup і завантаження**

In [65]:
# Install PostgreSQL
!apt-get update -qq
!apt-get install -y -qq postgresql postgresql-contrib

# Start PostgreSQL
!service postgresql start

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]

In [66]:
# Set password for the default postgres user
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

# Create database for the homework
!sudo -u postgres createdb hw3_db

ALTER ROLE
createdb: error: database creation failed: ERROR:  database "hw3_db" already exists

In [67]:
%pip install -q sqlalchemy psycopg2-binary pandas pyarrow

In [68]:
import pandas as pd
import os
import psycopg2
import kagglehub
import importlib

from sqlalchemy import create_engine, text
from urllib.request import urlretrieve
from sqlalchemy import create_engine, text
pd = importlib.reload(pd)
import sys
print(sys.version)

3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]

In [69]:
!sudo -u postgres createdb hw4_db

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/hw4_db",
    future=True
)

with engine.connect() as conn:
    version = conn.execute(
        text("SELECT version()")
    ).scalar_one()

    print(version)

createdb: error: database creation failed: ERROR:  database "hw4_db" already exists
PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

In [70]:
dataset_dir = kagglehub.dataset_download(
    "olistbr/brazilian-ecommerce"
)

print(dataset_dir)

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
/kaggle/input/brazilian-ecommerce

In [71]:
files = {
    'olist_customers_raw': 'olist_customers_dataset.csv',
    'olist_orders_raw': 'olist_orders_dataset.csv',
    'olist_order_items_raw': 'olist_order_items_dataset.csv',
    'olist_products_raw': 'olist_products_dataset.csv',
    'olist_sellers_raw': 'olist_sellers_dataset.csv',
    'olist_order_reviews_raw': 'olist_order_reviews_dataset.csv',
}

for table_name, file_name in files.items():
    path = os.path.join(dataset_dir, file_name)
    df = pd.read_csv(path)
    df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10_000)
    print(table_name, df.shape)

olist_customers_raw (99441, 5)
olist_orders_raw (99441, 8)
olist_order_items_raw (112650, 7)
olist_products_raw (32951, 9)
olist_sellers_raw (3095, 4)
olist_order_reviews_raw (99224, 7)

In [72]:
create_typed_sql = """
DROP TABLE IF EXISTS customer_segments    CASCADE;
DROP TABLE IF EXISTS seller_score         CASCADE;
DROP TABLE IF EXISTS seller_alerts        CASCADE;
DROP TABLE IF EXISTS olist_customer_dim   CASCADE;
DROP TABLE IF EXISTS olist_order_reviews  CASCADE;
DROP TABLE IF EXISTS olist_order_items    CASCADE;
DROP TABLE IF EXISTS olist_orders         CASCADE;
DROP TABLE IF EXISTS olist_customers      CASCADE;
DROP TABLE IF EXISTS olist_products       CASCADE;
DROP TABLE IF EXISTS olist_sellers        CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);

CREATE INDEX idx_olist_customers_unique_id
    ON olist_customers (customer_unique_id);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);

CREATE INDEX idx_olist_order_items_seller_order
    ON olist_order_items (seller_id, order_id);

CREATE TABLE olist_order_reviews (
    review_row_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id                TEXT,
    order_id                 TEXT NOT NULL REFERENCES olist_orders(order_id),
    review_score             SMALLINT CHECK (review_score BETWEEN 1 AND 5),
    review_comment_title     TEXT,
    review_comment_message   TEXT,
    review_creation_date     TIMESTAMP,
    review_answer_timestamp  TIMESTAMP
);

CREATE INDEX idx_olist_order_reviews_order_id
    ON olist_order_reviews (order_id);

"""

with engine.begin() as conn:
    conn.execute(text(create_typed_sql))

print("Typed table created.")

Typed table created.

In [73]:
check_typed_sql = """

SELECT *
FROM olist_orders
LIMIT 10;

"""

pd.read_sql(check_typed_sql, engine)

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [74]:
insert_typed_sql = """

TRUNCATE TABLE
    olist_order_reviews,
    olist_order_items,
    olist_orders,
    olist_customers,
    olist_products,
    olist_sellers;

INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;

INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;

INSERT INTO olist_order_reviews (
    review_id,
    order_id,
    review_score,
    review_comment_title,
    review_comment_message,
    review_creation_date,
    review_answer_timestamp
)
SELECT
    review_id,
    order_id,
    review_score::SMALLINT,
    review_comment_title,
    review_comment_message,
    review_creation_date::TIMESTAMP,
    review_answer_timestamp::TIMESTAMP
FROM olist_order_reviews_raw;
"""

with engine.begin() as conn:
    conn.execute(text(insert_typed_sql))
print("Data inserted")

Data inserted

In [75]:
check_typed_sql = """

SELECT *
FROM olist_orders
LIMIT 10;

"""

pd.read_sql(check_typed_sql, engine)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23

In [76]:
check_tables_sql = """

SELECT 'customers' AS table_name, COUNT(*) AS n_rows FROM olist_customers
UNION ALL SELECT 'orders', COUNT(*) FROM olist_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM olist_order_items
UNION ALL SELECT 'products', COUNT(*) FROM olist_products
UNION ALL SELECT 'sellers', COUNT(*) FROM olist_sellers
UNION ALL SELECT 'reviews', COUNT(*) FROM olist_order_reviews
ORDER BY table_name;
"""

pd.read_sql(check_tables_sql, engine)

    table_name  n_rows
0    customers   99441
1  order_items  112650
2       orders   99441
3     products   32951
4      reviews   99224
5      sellers    3095

# **Завдання 2. DML-запити з PostgreSQL-фічами**

In [77]:
# 2.1. INSERT ... RETURNING: створення alert для продавця з найбільшою кількістю запізнень

create_alerts_sql = """

DROP TABLE IF EXISTS seller_alerts CASCADE;

CREATE TABLE seller_alerts (
    alert_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seller_id  TEXT NOT NULL REFERENCES olist_sellers(seller_id),
    alert_type TEXT NOT NULL CHECK (alert_type IN ('late_delivery', 'low_rating', 'data_quality')),
    severity   SMALLINT NOT NULL CHECK (severity BETWEEN 1 AND 5),
    details    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

WITH seller_orders AS (
    SELECT DISTINCT
        oi.seller_id,
        oi.order_id
    FROM olist_order_items AS oi
),
late_sellers AS (
    SELECT
        so.seller_id,
        COUNT(DISTINCT o.order_id) AS late_orders
    FROM seller_orders AS so
    JOIN olist_orders AS o
        ON o.order_id = so.order_id
    WHERE o.order_delivered_customer_date IS NOT NULL
      AND o.order_estimated_delivery_date IS NOT NULL
      AND o.order_delivered_customer_date::DATE > o.order_estimated_delivery_date::DATE
    GROUP BY so.seller_id
    ORDER BY late_orders DESC, so.seller_id
    LIMIT 1
)
INSERT INTO seller_alerts (seller_id, alert_type, severity, details)
SELECT
    seller_id,
    'late_delivery',
    4,
    'Seller has ' || late_orders || ' late delivered orders in the loaded dataset'
FROM late_sellers
RETURNING alert_id, seller_id, alert_type, severity, created_at;

"""

with engine.begin() as conn:
    conn.execute(text(create_alerts_sql))
print("alerts_sql created")

alerts_sql created

In [78]:
alert = """

SELECT *
FROM seller_alerts
LIMIT 5;
"""

pd.read_sql(alert, engine)

,alert_id,seller_id,alert_type,severity,details,created_at
0,1,4a3ca9315b744ce9f8e9374361493884,late_delivery,4,Seller has 172 late delivered orders in the lo...,2026-10-15 06:17:05.390972+00:00

In [79]:
check_seller_alerts = """

SELECT
  count(*) AS n_rows
FROM seller_alerts
"""

pd.read_sql(check_seller_alerts,engine)

   n_rows
0       1

Конструкція RETURNING дозволяє одразу отримати інформацію про створений запис (alert_id, seller_id, alert_type, severity, created_at) без додаткового SELECT-запиту.

Отримані дані можна використати як audit-log у notebook для відстеження того, який alert було створено, для якого продавця та коли саме.

In [80]:
# 2.2. INSERT ... ON CONFLICT DO UPDATE: idempotent upsert агрегованих seller-score

upsert_score_sql = """
DROP TABLE IF EXISTS seller_score CASCADE;

CREATE TABLE seller_score (
    seller_id   TEXT PRIMARY KEY REFERENCES olist_sellers(seller_id),
    avg_rating  NUMERIC(3, 2),
    n_reviews   INTEGER NOT NULL DEFAULT 0 CHECK (n_reviews >= 0),
    tier        TEXT CHECK (tier IN ('gold', 'silver', 'bronze')),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

WITH seller_orders AS (
    SELECT DISTINCT
        oi.seller_id,
        oi.order_id
    FROM olist_order_items AS oi
),
review_per_order AS (
    SELECT
        rv.order_id,
        AVG(rv.review_score)::NUMERIC(3, 2) AS order_review_score
    FROM olist_order_reviews AS rv
    WHERE rv.review_score IS NOT NULL
    GROUP BY rv.order_id
),
seller_rating AS (
    SELECT
        so.seller_id,
        AVG(rpo.order_review_score)::NUMERIC(3, 2) AS avg_rating,
        COUNT(rpo.order_id) AS n_reviews
    FROM seller_orders AS so
    LEFT JOIN review_per_order AS rpo
        ON rpo.order_id = so.order_id
    GROUP BY so.seller_id
)
INSERT INTO seller_score (seller_id, avg_rating, n_reviews, tier)
SELECT
    seller_id,
    avg_rating,
    n_reviews,
    CASE
        WHEN avg_rating IS NULL THEN NULL
        WHEN avg_rating >= 4.5 THEN 'gold'
        WHEN avg_rating >= 3.5 THEN 'silver'
        ELSE 'bronze'
    END AS tier
FROM seller_rating
ON CONFLICT (seller_id) DO UPDATE
SET avg_rating = EXCLUDED.avg_rating,
    n_reviews  = EXCLUDED.n_reviews,
    tier       = EXCLUDED.tier,
    updated_at = NOW()
RETURNING seller_id, avg_rating, n_reviews, tier, updated_at;
"""

with engine.begin() as conn:
    conn.execute(text(upsert_score_sql))
print("upsert_score_sql created")

upsert_score_sql created

In [81]:
df = pd.read_sql("""
    SELECT tier, COUNT(*) AS sellers_count
    FROM seller_score
    GROUP BY tier
    ORDER BY tier;
""", engine)

display(df)

     tier  sellers_count
0  bronze            539
1    gold            983
2  silver           1568
3    None              5

### 2.2. INSERT ... ON CONFLICT DO UPDATE

У цьому запиті ми розрахували середній рейтинг кожного продавця та розподілили продавців на категорії `gold`, `silver` і `bronze`.

- `SELECT DISTINCT` використовується, щоб одне замовлення продавця враховувалося лише один раз, незалежно від кількості товарів.
- Відгуки спочатку агрегуються на рівні `order_id`, щоб уникнути дублювання оцінок під час об'єднання таблиць.
- `ON CONFLICT (seller_id) DO UPDATE` дозволяє повторно запускати запит без створення дублікатів. Наявні записи оновлюються, а нові додаються.
- Якщо продавець не має оцінених замовлень, його `avg_rating = NULL`, `n_reviews = 0` і `tier = NULL`.

**Обмеження датасету:** відгуки в Olist належать замовленню, а не конкретному продавцю. Тому, якщо в одному замовленні були товари кількох продавців, одна оцінка враховується для кожного з них. Це спрощення прийнятне для навчального завдання, але може впливати на точність рейтингу продавців.

In [82]:
# 2.3. UPDATE ... FROM: оновлення прапорця запізнення в olist_orders

delivery_flags_sql = """

ALTER TABLE olist_orders
    ADD COLUMN IF NOT EXISTS is_late BOOLEAN NOT NULL DEFAULT FALSE;

WITH delivery_flags AS (
    SELECT
        order_id,
        (
            order_delivered_customer_date IS NOT NULL
            AND order_estimated_delivery_date IS NOT NULL
            AND order_delivered_customer_date::DATE > order_estimated_delivery_date::DATE
        ) AS is_late_calc
    FROM olist_orders
)
UPDATE olist_orders AS o
SET is_late = f.is_late_calc
FROM delivery_flags AS f
WHERE f.order_id = o.order_id
RETURNING o.order_id, o.customer_id, o.is_late;
"""

with engine.begin() as conn:
    conn.execute(text(delivery_flags_sql))
print("delivery_flags_sql created")

delivery_flags_sql created

In [83]:
flags = """
SELECT
  COUNT (*) AS n_rows,
  COUNT (*) FILTER (WHERE o.is_late IS TRUE) AS true_late,
  COUNT (*) FILTER (WHERE o.is_late IS FALSE) AS false_late,
  ROUND(
    count (*) FILTER (WHERE o.is_late IS TRUE) * 100.0 / NULLIF(count(*), 0),
    4
  ) AS prcnt_true
FROM olist_orders o
"""

pd.read_sql(flags, engine)

   n_rows  true_late  false_late  prcnt_true
0   99441       6535       92906      6.5717

In [84]:
# 2.4. DELETE ... RETURNING: контрольоване видалення застарілих alert-ів

delete_alerts_sql = """
DELETE FROM seller_alerts
WHERE created_at < NOW() - INTERVAL '30 days'
RETURNING alert_id, seller_id, alert_type, created_at;
"""

with engine.begin() as conn:
    result = conn.execute(text(delete_alerts_sql))
    df_deleted = pd.DataFrame(result.fetchall(), columns=result.keys())

display(df_deleted)

Empty DataFrame
Columns: [alert_id, seller_id, alert_type, created_at]
Index: []

Порожній результат є допустимим, оскільки в таблиці seller_alerts може не бути записів, створених понад 30 днів тому.

# **Завдання 3. CREATE TABLE customer_segments**

In [85]:
dedup_cust_dim = """

DROP TABLE IF EXISTS customer_segments CASCADE;
DROP TABLE IF EXISTS olist_customer_dim CASCADE;

CREATE TABLE olist_customer_dim (
    customer_unique_id TEXT PRIMARY KEY,
    latest_customer_id TEXT REFERENCES olist_customers(customer_id),
    customer_state     CHAR(2),
    customer_city      TEXT
);

INSERT INTO olist_customer_dim (
    customer_unique_id,
    latest_customer_id,
    customer_state,
    customer_city
)
SELECT DISTINCT ON (c.customer_unique_id)
    c.customer_unique_id,
    c.customer_id AS latest_customer_id,
    c.customer_state,
    c.customer_city
FROM olist_customers AS c
LEFT JOIN olist_orders AS o
    ON o.customer_id = c.customer_id
ORDER BY
    c.customer_unique_id,
    o.order_purchase_timestamp DESC NULLS LAST,
    c.customer_id;
"""

with engine.begin() as conn:
    result = conn.execute(text(dedup_cust_dim))

In [86]:
customer_segments_sql = """
DROP TABLE IF EXISTS customer_segments CASCADE;

CREATE TABLE customer_segments (
    segment_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    customer_unique_id  TEXT NOT NULL,
    segment_name        TEXT NOT NULL
        CHECK (segment_name IN ('VIP', 'regular', 'new', 'inactive')),

    rfm_score           SMALLINT NOT NULL
        CHECK (rfm_score BETWEEN 1 AND 5),

    recency_days        INTEGER
        CHECK (recency_days IS NULL OR recency_days >= 0),

    monetary_value      NUMERIC(12, 2) NOT NULL DEFAULT 0
        CHECK (monetary_value >= 0),

    n_orders            INTEGER NOT NULL DEFAULT 0
        CHECK (n_orders >= 0),

    assigned_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (customer_unique_id)
);

ALTER TABLE customer_segments
    ADD CONSTRAINT fk_customer_segments_customer_unique
    FOREIGN KEY (customer_unique_id)
    REFERENCES olist_customer_dim(customer_unique_id)
    ON DELETE CASCADE;

"""

with engine.begin() as conn:
    result = conn.execute(text(customer_segments_sql))

In [87]:
customer_segments_sql_filled = """

WITH reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
order_totals AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(oi.price + oi.freight_value), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp
),
customer_stats AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT ot.order_id) AS n_orders,
        COALESCE(SUM(ot.order_total), 0)::NUMERIC(12, 2) AS monetary_value,
        MAX(ot.order_date) AS last_order_date
    FROM olist_customer_dim AS cd
    JOIN olist_customers AS c
        ON c.customer_unique_id = cd.customer_unique_id
    LEFT JOIN order_totals AS ot
        ON ot.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
),
segmented AS (
    SELECT
        cs.customer_unique_id,
        cs.n_orders,
        cs.monetary_value,
        CASE
            WHEN cs.last_order_date IS NULL THEN NULL
            ELSE (rd.as_of_date - cs.last_order_date)::INTEGER
        END AS recency_days,
        CASE
            WHEN cs.monetary_value >= 1000 THEN 'VIP'
            WHEN cs.last_order_date IS NOT NULL
                 AND (rd.as_of_date - cs.last_order_date)::INTEGER <= 90
                 AND cs.n_orders = 1 THEN 'new'
            WHEN cs.n_orders >= 2 OR cs.monetary_value >= 100 THEN 'regular'
            ELSE 'inactive'
        END AS segment_name,
        CASE
            WHEN cs.monetary_value >= 1000 THEN 5
            WHEN cs.monetary_value >= 500  THEN 4
            WHEN cs.n_orders >= 2          THEN 3
            WHEN cs.n_orders = 1           THEN 2
            ELSE 1
        END::SMALLINT AS rfm_score
    FROM customer_stats AS cs
    CROSS JOIN reference_date AS rd
)
INSERT INTO customer_segments (
    customer_unique_id,
    segment_name,
    rfm_score,
    recency_days,
    monetary_value,
    n_orders
)
SELECT
    customer_unique_id,
    segment_name,
    rfm_score,
    recency_days,
    monetary_value,
    n_orders
FROM segmented
ON CONFLICT (customer_unique_id) DO UPDATE
SET segment_name   = EXCLUDED.segment_name,
    rfm_score      = EXCLUDED.rfm_score,
    recency_days   = EXCLUDED.recency_days,
    monetary_value = EXCLUDED.monetary_value,
    n_orders       = EXCLUDED.n_orders,
    assigned_at    = NOW()
RETURNING
    customer_unique_id,
    segment_name,
    rfm_score,
    recency_days,
    monetary_value,
    n_orders;

"""

with engine.begin() as conn:
    result = conn.execute(text(customer_segments_sql_filled))

In [88]:
check_constraints_sql = """
SELECT
    conname,
    contype,
    pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'customer_segments'::regclass
ORDER BY conname;
"""

pd.read_sql(check_constraints_sql, engine)

,conname,contype,definition
0,customer_segments_customer_unique_id_key,u,UNIQUE (customer_unique_id)
1,customer_segments_monetary_value_check,c,CHECK ((monetary_value >= (0)::numeric))
2,customer_segments_n_orders_check,c,CHECK ((n_orders >= 0))
3,customer_segments_pkey,p,PRIMARY KEY (segment_id)
4,customer_segments_recency_days_check,c,CHECK (((recency_days IS NULL) OR (recency_day...
5,customer_segments_rfm_score_check,c,CHECK (((rfm_score >= 1) AND (rfm_score <= 5)))
6,customer_segments_segment_name_check,c,"CHECK ((segment_name = ANY (ARRAY['VIP'::text,..."
7,fk_customer_segments_customer_unique,f,FOREIGN KEY (customer_unique_id) REFERENCES ol...

1. `customer_unique_id` використовуємо, щоб враховувати всі замовлення одного покупця, а не кожне окремо.
2. `olist_customer_dim` потрібна, щоб мати унікальні ID покупців для зв'язку через FK.
3. `reference_date` беремо з датасету, бо дані історичні й поточна дата спотворить розрахунки.
4. `ON CONFLICT` дозволяє повторно запускати запит без дублікатів, оновлюючи вже наявні записи.

# **Завдання 4. JOIN-запити з business-interpretation**

In [89]:
#Приклад 4.1. INNER JOIN: топ категорій за revenue і seller-state
join_1= """
SELECT
    p.product_category_name,
    s.seller_state,
    COUNT(DISTINCT oi.order_id) AS n_orders,
    SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS revenue
FROM olist_order_items AS oi
JOIN olist_orders AS o
    ON o.order_id = oi.order_id
JOIN olist_products AS p
    ON p.product_id = oi.product_id
JOIN olist_sellers AS s
    ON s.seller_id = oi.seller_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name, s.seller_state
ORDER BY revenue DESC NULLS LAST
LIMIT 10;
"""
pd.read_sql(join_1,engine)

    product_category_name seller_state  n_orders     revenue
0         cama_mesa_banho           SP      8214  1070048.14
1      relogios_presentes           SP      4494  1016168.80
2            beleza_saude           SP      5684   790967.66
3           esporte_lazer           SP      4772   680165.54
4        moveis_decoracao           SP      4597   605650.63
5              cool_stuff           SP      2621   484196.53
6   utilidades_domesticas           SP      4021   471810.66
7              automotivo           SP      3018   438833.22
8  informatica_acessorios           SP      2783   388506.42
9                   bebes           SP      1981   339129.74

In [90]:
#Приклад 4.2. LEFT JOIN + COALESCE: customer-level features без множення review

join_2 = """
WITH order_totals AS (
    SELECT
        o.order_id,
        c.customer_unique_id,
        SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.order_id,
        c.customer_unique_id
),
review_per_order AS (
    SELECT
        rv.order_id,
        AVG(rv.review_score)::NUMERIC(3, 2) AS order_review_score
    FROM olist_order_reviews AS rv
    WHERE rv.review_score IS NOT NULL
    GROUP BY rv.order_id
),
customer_stats AS (
    SELECT
        ot.customer_unique_id,
        COUNT(DISTINCT ot.order_id) AS n_orders,
        COALESCE(SUM(ot.order_total), 0)::NUMERIC(12, 2) AS total_spend,
        AVG(rpo.order_review_score)::NUMERIC(3, 2) AS avg_review_score
    FROM order_totals AS ot
    LEFT JOIN review_per_order AS rpo
        ON rpo.order_id = ot.order_id
    GROUP BY ot.customer_unique_id
)
SELECT
    cd.customer_unique_id,
    cd.customer_state,
    COALESCE(cs.n_orders, 0) AS n_orders,
    COALESCE(cs.total_spend, 0)::NUMERIC(12, 2) AS total_spend,
    COALESCE(cs.avg_review_score, 0)::NUMERIC(3, 2) AS avg_review_score
FROM olist_customer_dim AS cd
LEFT JOIN customer_stats AS cs
    ON cs.customer_unique_id = cd.customer_unique_id
ORDER BY total_spend DESC NULLS LAST
LIMIT 20;

"""

pd.read_sql(join_2,engine)

,customer_unique_id,customer_state,n_orders,total_spend,avg_review_score
0,0a0a92112bd4c708ca5fde585afaa872,RJ,1,13664.08,1.0
1,da122df9eeddfedc1dc1f5349a1a690c,RJ,2,7571.63,5.0
2,763c8b1c9c68a0229c42c9fc6f662b93,ES,1,7274.88,1.0
3,dc4802a71eae9be1dd28f5d788ceb526,MS,1,6929.31,5.0
4,459bef486812aa25204be022145caa62,ES,1,6922.21,0.0
5,ff4159b92c40ebe40454e3e6a7c35ed6,SP,1,6726.66,5.0
6,4007669dec559734d6f53e029e360987,MG,1,6081.54,1.0
7,5d0a2980b292d049061542014e8960bf,GO,1,4809.44,1.0
8,eebb5dda148d3893cdaf5b5ca3040ccb,SP,1,4764.34,4.0
9,48e1ac109decbb87765a3eade6854098,PB,1,4681.78,5.0
10,c8460e4251689ba205045f3ea17884a1,RS,4,4655.88,4.0
11,edde2314c6c30e864a128ac95d6b2112,SP,1,4513.32,5.0
12,a229eba70ec1c2abef51f04987deb7a5,RJ,1,4445.50,5.0
13,edf81e1f3070b9dac83ec83dacdbb9bc,DF,1,4194.76,2.0
14,fa562ef24d41361e476e748681810e1e,MG,1,4175.26,5.0
15,ca27f3dac28fb1063faddd424c9d95fa,MG,1,4163.51,4.0
16,055ec572ac7f3c7bdd04a183830ebe59,SP,2,4053.08,1.0
17,5e713be0853d8986528d7869a0811d2b,PA,1,4042.74,5.0
18,58483a1c055dfb600f57c5b867174542,SP,1,4034.44,5.0
19,011875f0176909c5cf0b14a9138bb691,SP,1,4016.91,5.0

In [91]:
#Приклад 4.3. FULL OUTER JOIN: які штати присутні серед клієнтів і продавців

join_3 = """
WITH customer_states AS (
    SELECT customer_state AS state, COUNT(*) AS n_customers
    FROM olist_customers
    GROUP BY customer_state
), seller_states AS (
    SELECT seller_state AS state, COUNT(*) AS n_sellers
    FROM olist_sellers
    GROUP BY seller_state
)
SELECT
    COALESCE(c.state, s.state) AS state,
    c.n_customers,
    s.n_sellers,
    CASE
        WHEN c.state IS NOT NULL AND s.state IS NOT NULL THEN 'both'
        WHEN c.state IS NOT NULL THEN 'customers_only'
        ELSE 'sellers_only'
    END AS state_presence
FROM customer_states AS c
FULL OUTER JOIN seller_states AS s
    ON s.state = c.state
ORDER BY state;
"""

pd.read_sql(join_3,engine)

   state  n_customers  n_sellers  state_presence
0     AC           81        1.0            both
1     AL          413        NaN  customers_only
2     AM          148        1.0            both
3     AP           68        NaN  customers_only
4     BA         3380       19.0            both
5     CE         1336       13.0            both
6     DF         2140       30.0            both
7     ES         2033       23.0            both
8     GO         2020       40.0            both
9     MA          747        1.0            both
10    MG        11635      244.0            both
11    MS          715        5.0            both
12    MT          907        4.0            both
13    PA          975        1.0            both
14    PB          536        6.0            both
15    PE         1652        9.0            both
16    PI          495        1.0            both
17    PR         5045      349.0            both
18    RJ        12852      171.0            both
19    RN          485        5.0            both
20    RO          253        2.0            both
21    RR           46        NaN  customers_only
22    RS         5466      129.0            both
23    SC         3637      190.0            both
24    SE          350        2.0            both
25    SP        41746     1849.0            both
26    TO          280        NaN  customers_only

In [92]:
# Приклад 4.4. SELF JOIN: пари продавців з одного штату, але з різних міст

join_4 = """
SELECT
    s1.seller_id AS seller_a,
    s2.seller_id AS seller_b,
    s1.seller_state,
    s1.seller_city AS city_a,
    s2.seller_city AS city_b
FROM olist_sellers AS s1
JOIN olist_sellers AS s2
    ON s1.seller_state = s2.seller_state
   AND s1.seller_id < s2.seller_id
   AND s1.seller_city IS DISTINCT FROM s2.seller_city
ORDER BY s1.seller_state, seller_a, seller_b
LIMIT 20;
"""
pd.read_sql(join_3,engine)

   state  n_customers  n_sellers  state_presence
0     AC           81        1.0            both
1     AL          413        NaN  customers_only
2     AM          148        1.0            both
3     AP           68        NaN  customers_only
4     BA         3380       19.0            both
5     CE         1336       13.0            both
6     DF         2140       30.0            both
7     ES         2033       23.0            both
8     GO         2020       40.0            both
9     MA          747        1.0            both
10    MG        11635      244.0            both
11    MS          715        5.0            both
12    MT          907        4.0            both
13    PA          975        1.0            both
14    PB          536        6.0            both
15    PE         1652        9.0            both
16    PI          495        1.0            both
17    PR         5045      349.0            both
18    RJ        12852      171.0            both
19    RN          485        5.0            both
20    RO          253        2.0            both
21    RR           46        NaN  customers_only
22    RS         5466      129.0            both
23    SC         3637      190.0            both
24    SE          350        2.0            both
25    SP        41746     1849.0            both
26    TO          280        NaN  customers_only

In [93]:
# Приклад 4.5. Anti-join: замовлення без відгуку

join_5 = """
SELECT
    o.order_id,
    o.customer_id,
    o.order_status,
    o.order_purchase_timestamp
FROM olist_orders AS o
LEFT JOIN olist_order_reviews AS rv
    ON rv.order_id = o.order_id
WHERE rv.review_row_id IS NULL
ORDER BY o.order_purchase_timestamp
LIMIT 20;
"""

pd.read_sql(join_5,engine)

,order_id,customer_id,order_status,order_purchase_timestamp
0,cda873529ca7ab71f677d5ec11a40304,76c74aaff2f3f7355f46d9818ad092b8,shipped,2016-10-05 16:57:30
1,5da2004d85f2828349d887c989da2adc,95f592086150f0c95d3082aea047b816,delivered,2016-10-05 20:20:59
2,02190241f7190a1f3c7e0df95a749c6a,55c9044401ffab0c717f24405e2e042f,delivered,2016-10-07 10:52:22
3,0efd0bc268d34da3f01f4ff25a6d4335,95446917717bb58d553d107d0f1668f6,shipped,2016-10-07 15:53:31
4,c776863a93dc0740c6e7d78104b21413,1710b798ebdc5db6665c815b90a64999,delivered,2016-10-10 15:01:27
5,d730d8d0ea3149120703933fdf98b2d4,ce2a66464da8b80dedd7639a6e489a58,shipped,2017-01-13 20:12:41
6,05cd156f0f47579a36d7a52724fc31b8,976224a95faf328b17654b1b1411d5e1,delivered,2017-01-14 18:27:28
7,719b940ab2f1e351ffb14a0a02ffe3c4,ede9a1daf58d256c0d648ef7e1479010,delivered,2017-01-16 13:01:51
8,fbd82b1fe98967de0db29b6cf134d00a,45f5c9d984dbfa2105e3544cc85133bf,delivered,2017-01-18 08:55:36
9,171398a0cd843c65ac78aee9e05a1f49,f0244902c07b7c0799e468218579a925,delivered,2017-01-18 16:07:37
10,fcda3cc8210e746326864eb933641ccf,fee7cf49127308e2b5402c9984b6f1f6,delivered,2017-01-18 22:41:55
11,58a4317c14bcba43d0cf161f17e9db2b,e7f5b701d99a5eb91e57a970a75640f0,delivered,2017-01-30 11:55:23
12,ee55010a370e987f203499f435a59847,9f074c63790b0ef8b01c66fd67a97601,delivered,2017-01-30 15:17:47
13,91bcbd0102f5188ea47df5bcc83f3cad,0e63522224dc7d760139532f17a3634f,delivered,2017-01-31 02:29:51
14,5f6b520cff06f23c77386b75976256e9,38e08b021ffa6f71de788a0e30c9c65a,delivered,2017-01-31 11:58:52
15,ecfc862cb2fabd3d5f9c86117a9baff0,5bb03a9d99d476e8634520ceb63e08d6,delivered,2017-02-05 19:13:56
16,5f2dbe00a1732133a6809ae1af554123,f7b1d4b064c31b564fd39ad8bcb7cbdc,unavailable,2017-02-06 08:18:30
17,0c4d07bcd65a6ce95cbe8e8e228a98cf,30d6a066b7e76c8fd66610d4b36e891d,delivered,2017-02-06 12:15:34
18,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,delivered,2017-02-09 11:38:52
19,765388e7b3d416ffe810ade706854872,a7288cab9fc524abf65915630e66c73b,delivered,2017-02-09 13:52:13

# **Завдання 5. GROUP BY, HAVING і агрегати**

In [94]:
# Приклад 5.1. Revenue per product category з фільтром по revenue

rev_1 = """
SELECT
    p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS n_orders,
    SUM(oi.price)::NUMERIC(12, 2) AS gross_revenue,
    SUM(oi.freight_value)::NUMERIC(12, 2) AS freight,
    AVG(oi.price)::NUMERIC(8, 2) AS avg_item_price
FROM olist_order_items AS oi
JOIN olist_products AS p
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
HAVING SUM(oi.price) > 10000
ORDER BY gross_revenue DESC NULLS LAST
LIMIT 10;
"""

pd.read_sql(rev_1,engine)

    product_category_name  n_orders  gross_revenue    freight  avg_item_price
0            beleza_saude      8836     1258681.34  182566.73          130.16
1      relogios_presentes      5624     1205005.68  100535.93          201.14
2         cama_mesa_banho      9417     1036988.68  204693.04           93.30
3           esporte_lazer      7720      988048.97  168607.51          114.34
4  informatica_acessorios      6689      911954.32  147318.08          116.51
5        moveis_decoracao      6449      729762.49  172749.30           87.56
6              cool_stuff      3632      635290.85   84039.10          167.36
7   utilidades_domesticas      5884      632248.66  146149.11           90.79
8              automotivo      3897      592720.11   92664.21          139.96
9      ferramentas_jardim      3518      485256.46   98962.75          111.63

In [95]:
# Приклад 5.2. AOV per customer-state тільки для штатів із достатньою кількістю замовлень

rev_2 = """
WITH order_totals AS (
    SELECT
        o.order_id,
        c.customer_state,
        SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.order_id,
        c.customer_state
)
SELECT
    customer_state,
    COUNT(*) AS n_orders,
    SUM(order_total)::NUMERIC(12, 2) AS gmv,
    (SUM(order_total) / NULLIF(COUNT(*), 0))::NUMERIC(8, 2) AS aov
FROM order_totals
GROUP BY customer_state
HAVING COUNT(*) >= 100
ORDER BY aov DESC NULLS LAST;
"""

pd.read_sql(rev_2,engine)

   customer_state  n_orders         gmv     aov
0              PB       532   140987.81  265.01
1              AL       411    96229.40  234.13
2              RO       247    57558.02  233.03
3              PA       970   217647.11  224.38
4              TO       279    61354.42  219.91
5              PI       493   108132.28  219.34
6              SE       345    73032.32  211.69
7              RN       482   101895.08  211.40
8              CE      1327   275606.30  207.69
9              MT       903   186168.96  206.17
10             MA       740   151171.99  204.29
11             PE      1648   322237.69  195.53
12             MS       709   135956.67  191.76
13             AM       147    27835.73  189.36
14             BA      3358   611506.67  182.10
15             GO      2007   347706.93  173.25
16             SC      3612   610213.60  168.94
17             RJ     12762  2129681.98  166.88
18             DF      2125   353229.44  166.23
19             RS      5432   885826.76  163.08
20             MG     11544  1856161.49  160.79
21             ES      2025   324801.91  160.40
22             PR      4998   800935.44  160.25
23             SP     41375  5921678.12  143.12

`WHERE` фільтрує окремі рядки до групування, а `HAVING` фільтрує вже згруповані дані.

Наприклад, через `WHERE` можна вибрати товари з ціною понад 100, а через `HAVING SUM(oi.price) > 10000` залишити лише ті категорії, загальна сума продажів яких перевищує 10 000.

In [96]:
# Приклад 5.3. Категорії, які купував реальний покупець, через STRING_AGG
rev_3 = """
SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS n_orders,
    SUM(oi.price)::NUMERIC(12, 2) AS total_spend,
    STRING_AGG(
        DISTINCT COALESCE(p.product_category_name, '(unknown)'),
        ', ' ORDER BY COALESCE(p.product_category_name, '(unknown)')
    ) AS categories
FROM olist_customers AS c
JOIN olist_orders AS o
    ON o.customer_id = c.customer_id
JOIN olist_order_items AS oi
    ON oi.order_id = o.order_id
LEFT JOIN olist_products AS p
    ON p.product_id = oi.product_id
GROUP BY c.customer_unique_id
HAVING COUNT(DISTINCT o.order_id) >= 1
ORDER BY total_spend DESC NULLS LAST
LIMIT 20;
"""

pd.read_sql(rev_3,engine)

,customer_unique_id,n_orders,total_spend,categories
0,0a0a92112bd4c708ca5fde585afaa872,1,13440.00,telefonia_fixa
1,da122df9eeddfedc1dc1f5349a1a690c,2,7388.00,eletroportateis
2,763c8b1c9c68a0229c42c9fc6f662b93,1,7160.00,telefonia_fixa
3,dc4802a71eae9be1dd28f5d788ceb526,1,6735.00,utilidades_domesticas
4,459bef486812aa25204be022145caa62,1,6729.00,pcs
5,ff4159b92c40ebe40454e3e6a7c35ed6,1,6499.00,artes
6,4007669dec559734d6f53e029e360987,1,5934.60,agro_industria_e_comercio
7,eebb5dda148d3893cdaf5b5ca3040ccb,1,4690.00,eletroportateis
8,5d0a2980b292d049061542014e8960bf,1,4599.90,cool_stuff
9,48e1ac109decbb87765a3eade6854098,1,4590.00,pcs
10,a229eba70ec1c2abef51f04987deb7a5,1,4400.00,relogios_presentes
11,edde2314c6c30e864a128ac95d6b2112,1,4399.87,instrumentos_musicais
12,fa562ef24d41361e476e748681810e1e,1,4099.99,consoles_games
13,c8460e4251689ba205045f3ea17884a1,4,4080.00,telefonia
14,ca27f3dac28fb1063faddd424c9d95fa,1,4059.00,esporte_lazer
15,055ec572ac7f3c7bdd04a183830ebe59,2,3999.98,automotivo
16,011875f0176909c5cf0b14a9138bb691,1,3999.90,relogios_presentes
17,edf81e1f3070b9dac83ec83dacdbb9bc,1,3999.00,eletroportateis
18,5e713be0853d8986528d7869a0811d2b,1,3980.00,(unknown)
19,f0767ae738c3d90e7b737d7b8b8bb4d1,1,3930.00,ferramentas_jardim

# **Завдання 6. Set operations, підзапит/window і Reflection**

In [97]:
# Приклад 6.1. Усі state-коди, що є у клієнтів або продавців

setop_1 = """
SELECT customer_state AS state, 'customer' AS role
FROM olist_customers

UNION

SELECT seller_state AS state, 'seller' AS role
FROM olist_sellers
ORDER BY state, role;
"""
pd.read_sql(setop_1,engine)

   state      role
0     AC  customer
1     AC    seller
2     AL  customer
3     AM  customer
4     AM    seller
5     AP  customer
6     BA  customer
7     BA    seller
8     CE  customer
9     CE    seller
10    DF  customer
11    DF    seller
12    ES  customer
13    ES    seller
14    GO  customer
15    GO    seller
16    MA  customer
17    MA    seller
18    MG  customer
19    MG    seller
20    MS  customer
21    MS    seller
22    MT  customer
23    MT    seller
24    PA  customer
25    PA    seller
26    PB  customer
27    PB    seller
28    PE  customer
29    PE    seller
30    PI  customer
31    PI    seller
32    PR  customer
33    PR    seller
34    RJ  customer
35    RJ    seller
36    RN  customer
37    RN    seller
38    RO  customer
39    RO    seller
40    RR  customer
41    RS  customer
42    RS    seller
43    SC  customer
44    SC    seller
45    SE  customer
46    SE    seller
47    SP  customer
48    SP    seller
49    TO  customer

In [100]:
# Приклад 6.2. Штати, у яких є і клієнти, і продавці

setop_2 = """
SELECT customer_state AS state
FROM olist_customers

INTERSECT

SELECT seller_state AS state
FROM olist_sellers
ORDER BY state
LIMIT 5;
"""
pd.read_sql(setop_2,engine)

  state
0    AC
1    AM
2    BA
3    CE
4    DF

In [101]:
# Приклад 6.3. Найновіше замовлення кожного реального покупця через ROW_NUMBER()
setop_3 = """
WITH ranked_orders AS (
    SELECT
        c.customer_unique_id,
        o.customer_id,
        o.order_id,
        o.order_purchase_timestamp,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_unique_id
            ORDER BY o.order_purchase_timestamp DESC, o.order_id DESC
        ) AS rn
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
)
SELECT
    customer_unique_id,
    customer_id,
    order_id,
    order_purchase_timestamp
FROM ranked_orders
WHERE rn = 1
ORDER BY customer_unique_id
LIMIT 20;
"""
pd.read_sql(setop_3,engine)

,customer_unique_id,customer_id,order_id,order_purchase_timestamp
0,0000366f3b9a7992bf8c76cfdf3221e2,fadbb3709178fc513abc1b2670aa1ad2,e22acc9c116caa3f2b7121bbb380d08e,2018-05-10 10:56:27
1,0000b849f77a49e4a4ce2b2a4ca5be3f,4cb282e167ae9234755102258dd52ee8,3594e05a005ac4d06a72673270ef9ec9,2018-05-07 11:11:27
2,0000f46a3911fa3c0805444483337064,9b3932a6253894a02c1df9d19004239f,b33ec3b699337181488304f362a6b734,2017-03-10 21:05:03
3,0000f6ccb0745a6a4b88665a16c9f078,914991f0c02ef0843c0e7010c819d642,41272756ecddd9a9ed0180413cc22fb6,2017-10-12 20:29:41
4,0004aac84e0df4da2b147fca70cf8255,47227568b10f5f58a524a75507e6992c,d957021f1127559cd947b62533f484f7,2017-11-14 19:45:42
5,0004bd2a26a76fe21f786e4fbd80607f,4a913a170c26e3c8052ed0202849b5a8,3e470077b690ea3e3d501cffb5e0c499,2018-04-05 19:33:16
6,00050ab1314c0e55a6ca13cf7181fecf,d2509c13692836fc0449e88cf9eb4858,d0028facea13f508e880202d7097a5a1,2018-04-20 12:57:23
7,00053a61a98854899e70ed204dd4bafe,a81ebb9b32f102298c0c89635b4b3154,44e608f2db00c74a1fe329de44416a4e,2018-02-28 11:15:41
8,0005e1862207bf6ccc02e4228effd9a0,3b37fb626fdf46cd99d37ec62afa88ff,ae76bef74b97bcb0b3e355e60d9a6f9c,2017-03-04 23:32:12
9,0005ef4cd20d2893f0d9fbd94d3c0d97,c59e8ff99836e90d8b457d4122dc34e9,01b330808c5819a6a3cb79b72f0b8288,2018-03-12 15:22:12
10,0006fdc98a402fceb4eb0ee528f6a8d4,2f29573c8cac5a7be11c5b649078f944,6681163e3dab91c549952b2845b20281,2017-07-18 09:23:10
11,00082cbe03e478190aadbea78542e933,9dec2d47e95677b616efe366f8bf9fb8,67503374d1fbcbe5e3a40324f703ffc8,2017-11-19 15:22:02
12,00090324bbad0e9342388303bb71ba0a,40f0183f7439212e8ce53dc6103dfb2f,85bf8863657bff31006811d45d1c8db9,2018-03-24 14:44:41
13,000949456b182f53c18b68d6babc79c1,64eb9409c29c87a0a90ee1e08ce05065,d342d7bad292d68d41d58ffb594cf431,2018-04-23 09:55:46
14,000a5ad9c4601d2bbdd9ed765d5213b3,be22f11baf346059cbe6556ef9c69070,f7fa5cf8386e51037856df1add3e1228,2017-08-11 13:45:15
15,000bfa1d2f1a41876493be685390d6d3,e36917a47d5bf39bd3f38bcafb3d438f,fd61441ba2a7b57e6342862e779b10b0,2017-09-29 14:46:58
16,000c8bdb58a29e7115cfc257230fb21b,0e114b02a45c9876080f3a9a19f51c16,34801c59d6ec5c5e89bfefb6ebef314d,2017-12-12 22:53:35
17,000d460961d6dbfa3ec6c9f5805769e1,4948d9d11ebcd4d241a0b291c15d5779,5fd641e5e16c3b056b1fb4dd6e429c43,2018-01-07 22:59:25
18,000de6019bb59f34c099a907c151d855,455f2e2988eaf87d7e2ba33b0a57969f,c6d61340bd8baeedca7cc8e7f7ec07e9,2017-08-17 19:10:33
19,000e309254ab1fc5ba99dd469d36bdb4,8866a052aebe7f7cee97bace65b379b2,c5d3fae065a8090bae39f4f34b14cd06,2018-06-25 09:53:57

REFLECTION
### Reflection

1. Найскладнішим був `FULL OUTER JOIN`, оскільки потрібно було розібратися, як об'єднувати таблиці, зберігаючи всі записи з обох сторін.

2. Найважче було сформулювати business-question для `SELF JOIN`, бо спочатку не зовсім розумів його практичне застосування.

3. Найкориснішим вважаю `ON CONFLICT`, оскільки він дозволяє повторно запускати запити без дублювання даних.

4. Window functions використовував би для пошуку останніх замовлень, ранжування клієнтів та аналізу повторних покупок у ML-проєктах.

5. У Olist є замовлення без відгуків, пропущені категорії товарів та ризик дублювання даних при JOIN.

6. `customer_unique_id` дозволяє враховувати всі покупки одного клієнта, тоді як `customer_id` може відрізнятися для кожного замовлення.

7. Грануляція `seller_id × order_id` потрібна, щоб один відгук не враховувався кілька разів через наявність декількох товарів у замовленні.

**Висновок:** робота допомогла краще зрозуміти JOIN, агрегацію даних та важливість правильної підготовки даних для ML.